'use client';
import { useState } from 'react';
import { ArrowUpRight, Search, ShoppingBag, SlidersHorizontal, MessageCircle, Truck } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectContent, SelectItem, SelectValue } from '@/components/ui/select';
import { ages, cover, money, stock, type Product } from '@/lib/types';
import { whatsappOrderUrl } from '@/lib/whatsapp';
export function Brand() { return <a href="/" className="brand" aria-label="Ghalia Store, accueil"><span className="brand-mark">g.</span><span>ghalia<span className="brand-store">STORE</span></span></a>; }
export default function Catalog({products,preview=false,error}:{products:Product[];preview?:boolean;error?:string}) {
  const [age,setAge]=useState('all'),[genre,setGenre]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState(''),[photo,setPhoto]=useState(0),[limit,setLimit]=useState(20);
  const filtered=products.filter(p=>(age==='all'||p.age_code===Number(age))&&(genre==='all'||p.genre===genre)&&`${p.titre} ${p.couleur||''}`.toLowerCase().includes(query.toLowerCase()));
  function open(p:Product) {setSelected(p);setPhoto(0);setSize(p.variants.length===1?p.variants[0].taille:'');}
  const available=selected?.variants.find(v=>v.taille===size)?.stock||0;
  return <><div className="announcement">Les petits looks, les grands sourires. <span>À Ouagadougou</span></div><header className="header"><Brand/><nav><a href="#collection">La collection</a><a href="/admin">Gérer la boutique <ArrowUpRight size={15}/></a></nav><a className="contact" href="https://wa.me/22656886505" target="_blank" rel="noreferrer"><MessageCircle size={19}/><span>Nous écrire</span></a></header>
  <main><section className="hero"><div className="hero-copy"><span className="eyebrow">DE 0 À 13 ANS · GHALIA STORE</span><h1>Petits looks.<br/><span>Grandes aventures.</span></h1><p>Des ensembles colorés pour jouer, grandir<br className="desktop"/> et profiter de chaque journée.</p><a href="#collection" className="primary">Découvrir la collection <ArrowUpRight size={20}/></a><div className="hero-note"><ShoppingBag size={17}/> Choisis ton coup de cœur, écris-nous sur WhatsApp.</div></div><div className="hero-photos"><div className="hero-image one"><img src="/photos/1.5_01.webp" alt="Ensemble jaune avec short pour enfant" fetchPriority="high"/><span>Un peu de soleil.</span></div><div className="hero-image two"><img src="/photos/3.2_01.webp" alt="Ensemble polo et jupe verte" fetchPriority="high"/></div><div className="hero-stamp">À chaque âge,<br/><strong>son style.</strong></div></div></section>
  <section className="catalog-section" id="collection"><div className="section-title"><div><span className="eyebrow">LE VESTIAIRE DES PETITS</span><h2>La collection</h2></div><p>{filtered.length} modèles à découvrir</p></div>
  {preview&&<div className="notice">Aperçu de la collection · Les prix et disponibilités seront affichés après leur saisie dans la boutique.</div>}
  <div className="age-tabs" aria-label="Filtrer par âge"><button className={age==='all'?'active':''} onClick={()=>{setAge('all');setLimit(20)}}>Tous les âges</button>{ages.map((a,i)=><button className={age===String(i+1)?'active':''} key={a} onClick={()=>{setAge(String(i+1));setLimit(20)}}>{a}</button>)}</div>
  <div className="filters"><label className="search"><Search size={19}/><input aria-label="Rechercher un article" placeholder="Un ensemble, une couleur…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(20)}}/></label><div className="genre-filter"><SlidersHorizontal size={17}/><Select value={genre} onValueChange={setGenre}><SelectTrigger aria-label="Filtrer par genre"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tous les styles</SelectItem><SelectItem value="fille">Fille</SelectItem><SelectItem value="garcon">Garçon</SelectItem><SelectItem value="mixte">Mixte</SelectItem></SelectContent></Select></div></div>
  {error?<div className="empty"><p role="alert">{error}</p><button className="primary" onClick={()=>location.reload()}>Réessayer</button></div>:filtered.length===0?<div className="empty"><ShoppingBag/><h3>Aucun article pour le moment</h3><p>{products.length?'Essaie une autre recherche ou une autre tranche d’âge.':'La collection arrive bientôt.'}</p></div>:<div className="product-grid">{filtered.slice(0,limit).map(p=><button className="product-card" key={p.id} onClick={()=>open(p)}><div className="product-photo">{cover(p)&&<img src={cover(p)} alt={p.titre} loading="lazy" width="600" height="800"/>}<span className="age-badge">{ages[p.age_code-1]}</span><span className="card-open"><ArrowUpRight size={21}/></span></div><div className="product-info"><span className="product-kind">{p.type_article||'Ensemble'}</span><h3>{p.titre}</h3><p>{p.prix?money(p.prix):'Prix à venir'}{!preview&&stock(p)===0&&<span className="out">Épuisé</span>}</p></div></button>)}</div>}
  {filtered.length>limit&&<div className="load-more"><button className="secondary" onClick={()=>setLimit(limit+20)}>Voir plus de modèles</button></div>}</section>
  <section className="service-strip"><div><Truck/><strong>À Ouagadougou</strong><span>Livraison organisée avec la boutique</span></div><div><MessageCircle/><strong>Un échange, tout simplement</strong><span>Ta commande se prépare sur WhatsApp</span></div><div><ShoppingBag/><strong>Pour tous les petits</strong><span>Quatre tranches d’âge, de 0 à 13 ans</span></div></section></main>
  <footer><Brand/><p>Le vestiaire de leurs belles journées.</p><a href="/admin">Administration <ArrowUpRight size={15}/></a></footer>
  <Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className="product-dialog">{selected&&<><div className="detail-images"><img src={[...selected.product_images].sort((a,b)=>a.position-b.position)[photo]?.url} alt={selected.titre}/>{selected.product_images.length>1&&<div className="thumbs">{[...selected.product_images].sort((a,b)=>a.position-b.position).map((im,i)=><button key={im.url} aria-label={`Photo ${i+1}`} aria-pressed={photo===i} onClick={()=>setPhoto(i)}><img src={im.url} alt=""/></button>)}</div>}</div><div className="detail-copy"><span className="eyebrow">{ages[selected.age_code-1]}</span><DialogTitle className="detail-title">{selected.titre}</DialogTitle><DialogDescription>{selected.description||'Un ensemble pour accompagner les journées des petits.'}</DialogDescription><p className="detail-price">{selected.prix?money(selected.prix):'Prix à venir'}</p>{selected.couleur&&<p>Couleur : {selected.couleur}</p>}<fieldset className="sizes"><legend>Taille</legend>{selected.variants.length?selected.variants.map(v=><button disabled={!v.stock||preview} className={size===v.taille?'chosen':''} key={v.taille} onClick={()=>setSize(v.taille)}>{v.taille}</button>):<p>Tailles à renseigner</p>}</fieldset>{!preview&&selected.prix&&available>0?<a className="primary whatsapp" target="_blank" rel="noreferrer" href={whatsappOrderUrl(selected,size)}><MessageCircle size={19}/> Commander sur WhatsApp</a>:<button className="primary" disabled>{preview?'Bientôt disponible':stock(selected)===0?'Article épuisé':'Choisis une taille'}</button>}<p className="detail-note">Disponibilité et livraison confirmées par la boutique.</p></div></>}</DialogContent></Dialog>
  </>;
}
